name: dragabyte
base: core22
version: "0.6.1"
summary: Disk usage scanner and bulk rename utility
description: |
  Dragabyte is a desktop utility for scanning folder usage,
  finding the biggest files, and performing bulk rename operations.

grade: stable
confinement: strict

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

apps:
  dragabyte:
    command: usr/bin/dragabyte
    desktop: usr/share/applications/dragabyte.desktop
    extensions: [gnome]

parts:
  build-app:
    plugin: dump
    source: .
    build-snaps:
      - node/20/stable
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    override-build: |
      set -eu
      npm ci
      npm run tauri build -- --config src-tauri/tauri.linux.conf.json --bundles deb
      dpkg -x src-tauri/target/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/
      sed -i -e "s|Icon=dragabyte|Icon=/usr/share/icons/hicolor/32x32/apps/dragabyte.png|g" \
        $SNAPCRAFT_PART_INSTALL/usr/share/applications/dragabyte.desktop
